function dameArrayDeValores() {

  var textoValores = '{"arrayAyudas":['
    + '   {"ambito":"0"           ,"texto":" PENDIENTE COGER OPCIONES "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"cirugiaMenor","texto":"cirugiaMenor--Paciente que acude porque necesita cita para control de CTEs. e inyectables. Se le da cita "},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--En el día de hoy se intenta contactar con el paciente, pero éste no responde"},'
    + '   {"ambito":"curas","texto":"Curas--Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":" AplicacionTTos--AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"aplicacionTtos","texto":"AplicacionTTos---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."},'
    + '   {"ambito":"ttoFisio","texto":"Fisio---Paciente con alta en Fisioterapia. Notable mejoría. Se le recomienda con la continuidad de los ejercicios en casa."}'

    + ' ] }';
  var arrValores = jQuery.parseJSON(textoValores);
  return arrValores;
}
